### ISSUE TITLE
description of natbib in README.md

### ISSUE THREAD

**Issue by rnuske** [katrinleinweber/PhD-thesis#1]
Since I am currently looking for a good way to deal with citations in markdown and tex myself, I was puzzled by the following statement in the `README.md` 
```
Let makefile call natbib for PDF version, but custom citation style references.csl with black links & shorter bibliography entries for print.
```

Pandoc states in its documentation about [citation rendering](https://pandoc.org/MANUAL.html#citation-rendering): 
* `natbib` and `pandoc-citeproc` are mutually exclusive
* pandoc uses the `pandoc-citeproc` filter for doing the citations if the `bibliography` is set and `natbib` or `biblatex` are *not* set

So i guess your makefile is calling the `pandoc-citeproc` filter with `references.csl` and `natbib` is not involved at all.

**Comment by katrinleinweber** [comment]
I think I experimented with `natbib` initially, but must have forgotten to update the docu when I changed the `makefile` code.

Thanks for notifying me about this :-)

**Comment by rnuske** [comment]
You're welcome.
It was a welcome trigger to deepen/test my understanding of pandoc's handling of citations .

**Comment by katrinleinweber** [comment]
It was pretty good then, and I'm sure it still is. Haven't used it much since then, sadly.
